#!/bin/bash

xdg-mime default chromium.desktop x-scheme-handler/https
xdg-mime default chromium.desktop x-scheme-handler/http
xdg-mime default chromium.desktop text/html
xdg-mime default Thunar.desktop inode/directory
xdg-mime default eog.desktop image/jpeg
xdg-mime default eog.desktop image/png
xdg-mime default eog.desktop image/gif
xdg-mime default org.gnome.FileRoller.desktop application/zip
xdg-mime default org.gnome.FileRoller.desktop application/x-gzip
