#!/bin/sh
# This is called by systemd after resuming

supply=`cat /sys/class/power_supply/ADP0/online`
if [ $supply -eq 0 ]; then
	battery=true
else
	battery=false
fi

# Run power saving script
/etc/pm/power.d/10-power_script $battery
# Restart NM so it reconnects to WiFi
systemctl restart NetworkManager.service
